# Generated by Django 3.2.4 on 2021-07-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelcost',
            name='hotel_rating',
        ),
    ]
