# Generated by Django 3.2.4 on 2021-07-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_calculator', '0002_remove_hotelcost_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='travell_cost',
            name='destination_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.destination'),
        ),
        migrations.AddField(
            model_name='travell_cost',
            name='source_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.source'),
        ),
    ]
