# Generated by Django 3.2.4 on 2021-09-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_calculator', '0004_hotelcost_hotel_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_cost_route', models.IntegerField()),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.vehicle_modes')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.route')),
                ('vehicle_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.vehicle_class')),
                ('vehicle_comfort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.vehicle_type')),
                ('vehicle_company_names', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_calculator.vehicle_company')),
            ],
        ),
    ]
